### PR TITLE
chore: Refactor vendor dependencies in modules

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
chore: Refactor vendor dependencies in modules

This is initial work on refactoring of modules. Before this PR, each module had its own vendor folder.
That means this repo holds vendor dependencies, which were multiple times duplicated. Problematic was update of any package, because it had to be changed in each go.mod file. 
This PR starts migration to just a single vendor folder, go.mod and go.sum files.
As an initial work I moved cmd folder to root of the repo and moved each cmd folder from packages there. Then the vendor, tests folder, go.mod, go.sum files are removed and moved to root of repository. 

The pkg folders of each module are intact, because it would be too much of changes for a single PR. They will be unified in follow up PRs.

**Release note**:
```
chore: Refactor vendor dependencies in modules
```

### CODE REVIEW

**Comment by ksimon1** [comment]
/retest
@akrejcir, @jcanocan, @0xFelix can you please review this?

**Comment by jcanocan** [comment]
This is a huge effort. Many thanks @ksimon1!
/lgtm

**Comment by akrejcir** [comment]
When you move the `main.go` files and test module files, you remove them in one commit and then add them again in a future commit. This makes it hard to review, to see if these files are the same.
Can you do the move in a single commit?

**Comment by ksimon1** [comment]
@akrejcir I updated the commits

**Comment by akrejcir** [comment]
Thanks!

/lgtm

**Review by 0xFelix — APPROVED** [review]
/lgtm

Looks good to me too! Let's get the rest cleaned up in another PR.

**Pull request merged**
