### PR TITLE
fix(CNV-50417): enable usage of a custom secret

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

Add a new parameter secret-name which allows user to define another secret than only "kubevirt-disk-uploader-credentials-tekton".

**Release note**:

```release-note
Add a new secret-name parameter
```

### CODE REVIEW

**Comment by codingben** [comment]
@ksimon1 Can you please review?

**Comment by ksimon1** [comment]
failing e2e tests will be fixed by https://github.com/kubevirt/kubevirt-tekton-tasks/pull/541

**Comment by codingben** [comment]
> failing e2e tests will be fixed by #541

Ack, thanks!

**Pull request merged**
